gpiozero_node:
  ros__parameters:
    pin_factory: auto
    pin_numbering: bcm
    
    gpio:
      button:
        type: digital_input
        pin: 17
        pull_up: true
        bounce_time: 0.01
        publish_rate_hz: 100.0
      light_enable:
        type: digital_output
        pin: 12
        active_high: true
        initial_value: false
      motor_enable:
        type: digital_output
        pin: 16
        active_high: true
        initial_value: false
      gimbal_enable:
        type: digital_output
        pin: 26
        active_high: true
        initial_value: false
      front_led_pwm:
        type: pwm_output
        pin: 14
        active_high: true
        initial_value: 0.0
        frequency: 100.0
      back_led_pwm:
        type: pwm_output
        pin: 15
        active_high: true
        initial_value: 0.0
        frequency: 100.0